### PR TITLE
Add support for PHPUnit 6

### PR DESCRIPTION
**Pull request by skler**

### CODE REVIEW

**Comment by craig-davis** [comment]
Hi @skler, 

Thanks for contributing. I'd love to see this merged. I haven't used 6 in an projects yet, and haven't investigated it. What's failing in this?

Thanks!

**Comment by maxleaver** [comment]
Just came across this issue and would love to see it merged. It looks like the issue is with a change to the namespace structure between PHPUnit <6 and PHPUnit 6. There's a suggested workaround on [this StackOverflow thread](https://stackoverflow.com/questions/42811164/class-phpunit-framework-testcase-not-found). They suggest the following for backward compatibility:

```
// backward compatibility
if (!class_exists('\PHPUnit\Framework\TestCase') &&
    class_exists('\PHPUnit_Framework_TestCase')) {
    class_alias('\PHPUnit_Framework_TestCase', 'PHPUnit\Framework\TestCase');
}
```

I can submit a PR to update the bootstrap file with this if you like. That should allow this PR to pass.

**Comment by craig-davis** [comment]
@maxleaver That'd be great! I've added you as a contributor. I'm not able to devote time to this project this week. If you'd like to draft that PR and merge it, go for it. Do good work and treat it as your own!

**Comment by maxleaver** [comment]
@skler I added class aliases to the test bootstrap file for the updated PHPUnit 6/DBUnit 3 namespaces in a separate PR. The namespace changes in this PR will break backwards compatibility, so the only change required is the updated composer.json. Since the change is so minor, I'll go ahead and make a separate PR with that small change and close this PR.

@craig-davis Is it ok to increment the version to 2.1.3 with the change mentioned above?

**Comment by craig-davis** [comment]
> Is it ok to increment the version to 2.1.3 with the change mentioned above?

Seems reasonable to me.  With PHPUnit 4 at the end of life, I'm not particularly worried about too much backwards compatibility with older PHPUnit. As long as we don't cause breakage for people with a `^2` specified in their composer for this project, I'm fine with continuing to move forward. Go for it!

Thanks again for the help with this project. It is very much appreciated.

**Comment by kwreczycki** [comment]
Is there any chance to merge this PR to master ?

**Comment by maxleaver** [comment]
> Is there any chance to merge this PR to master?

Absolutely. It just requires the minor change mentioned in my comment above. I had intended to do it, but it fell off my radar. I'll dust it off and create a new PR this week with the change.

**Comment by kwreczycki** [comment]
Ok, great ! So I look forward for it, integration tests can't wait...;) ! Thanks a lot !

**Comment by maxleaver** [comment]
@kwreczycki Just merged in the code for full PHPUnit 6/DBUnit 3 support and incremented the version to 2.1.3. Let me know if you run into any problems.

**Pull request closed without merging**
