### PR TITLE
Slim v3

### PR DESCRIPTION
**Pull request by jwelmac**
Upgrade Slim functions to match functionality for version 3.

### CODE REVIEW

**Comment by craig-davis** [comment]
I think it's time to make a new Slim2 branch, and then move develop and master to be Slim3. Anybody have any objections or concerns?

**Comment by khrizt** [comment]
That looks like a good option, but should we wait until tests pass to merge it to master?

**Comment by jwelmac** [comment]
Working on getting all the tests to pass. 
I think it would be a great idea to move Slim3 to the main branch.
Will update as soon as its all done.

**Comment by craig-davis** [comment]
Sounds great. Thanks! Great to see this project getting some attention. I really appreciate it.

**Comment by jwelmac** [comment]
All checks passed.

**Comment by craig-davis** [comment]
This looks like it's progressing well. Is it time to pull this in and make the Slim2 branch and move this to develop and master with a release?

**Comment by jwelmac** [comment]
‎I think that would be a good move.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Craig DavisSent: Wednesday, July 6, 2016 11:00 AMTo: there4/slim-test-helpersReply To: there4/slim-test-helpersCc: Jermaine McFarlane; AuthorSubject: Re: [there4/slim-test-helpers] Slim v3 (#31)This looks like it's progressing well. Is it time to pull this in and make the Slim2 branch and move this to develop and master with a release?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by craig-davis** [comment]
I've created [a new branch for version two of the framework](https://github.com/there4/slim-test-helpers/tree/framework-v2), and am preparing a new 2.1 release for this PR. 

Again, thanks for continuing to support this project!

**Comment by jwelmac** [comment]
You are most welcome. 
This has been a great helper for a project I am currently working on.

Keep up the great work!

**Pull request merged**
