### PR TITLE
Update dependencies to phpunit 5

### PR DESCRIPTION
**Pull request by khrizt**
Updating dependencies on composer.json for both phpunit (to 5.* version) and dbunit (to 2.* version)

### CODE REVIEW

**Comment by craig-davis** [comment]
Good point - It does look like PHPUnit 5 [has dropped support for PHP54](https://github.com/sebastianbergmann/phpunit/blob/master/composer.json#L23) and that Slim 2 [is still supporting PHP53](https://github.com/slimphp/Slim/blob/2.x/composer.json#L16). 

With PHP55 end of life coming next month, I'm tempted to go ahead and merge this. The new version of this project for Slim3 will need to be 56, 70 or newer. 

1. @khrizt Can you give me a quick summary of what we're gaining with a phpunit 5 upgrade? 
2. Does anyone else have an opinion about dropping support for php 53, 54, 55 (even though Slim 2 still supports it)?

**Comment by khrizt** [comment]
Well the gain is basically that we can write test for our code using all the new features of PHP 7 like scalar type hint. My code is using some of the features of PHP 7 but I can't use scalar type hint because I can't test the methods then... so for my is a big issue, but I understand that maybe someone still uses PHP 5.5 (I hope few people uses PHP 5.3 xD)

**Comment by khrizt** [comment]
Any new on this front?

**Comment by craig-davis** [comment]
@khrizt Just to confirm, are you using slim 2.x?

**Comment by khrizt** [comment]
Yes, I'm using Slim 2.6

**Comment by craig-davis** [comment]
@khrizt I haven't heard any complaints, so let's move forward with it. Can you please remove the 53 to 55 builds fromthe travis config, and add 7? After that, I think we can merge this. I've invited you as a contributor. Are you comfortable doing that and then making a new release?

**Comment by khrizt** [comment]
Sure, I'll try, no problem

**Comment by khrizt** [comment]
Ok, I've released version 0.9.5 with these changes. Thanks a lot!

**Pull request merged**
