### PR TITLE
Support for DbUnit

### PR DESCRIPTION
**Pull request by felixmaier1989**
I had the need to implement database unit test in my Slim app. Therefore I created a test case compatible with DbUnit.

### CODE REVIEW

**Comment by craig-davis** [comment]
This will be fantastic to have. I really appreciate you contributing. 

It looks like the build it failing for PSR2 issues. If you have time, can you run `vendor/bin/phpcs --standard=PSR2 --extensions=php src tests` and fix those issues? If not, I can attend to it next week.

Thanks!

**Comment by felixmaier1989** [comment]
I will within the next few days!

**Comment by craig-davis** [comment]
Excellent, thanks!

**Comment by felixmaier1989** [comment]
I've reformatted the code to suit your CS. Added unit tests. And ensured PHP 5.3 compatibility.

**Comment by craig-davis** [comment]
Nice work! Thanks! I added you as a contributor. Would you like to do the honors and merge it?

**Comment by felixmaier1989** [comment]
Hahaha, thanks for the honors :)

**Pull request merged**
