### PR TITLE
Fix Issue #34: Testing 'Internal Server Error (500)'

### PR DESCRIPTION
**Pull request by Starli0n**
PHPUnit Ok!

```
PHPUnit 5.5.2 by Sebastian Bergmann and contributors.

..................                                                18 / 18 (100%)

Time: 266 ms, Memory: 10.00MB

OK (18 tests, 34 assertions)
```

### CODE REVIEW

**Comment by Starli0n** [comment]
Sorry I was too hasty and I forgot to add some unit tests. 

I will do it next week. Anyway the Travis tests failed.

**Comment by Starli0n** [comment]
I had to change the lowest version of Slim (~3.1) as the `process()` method did not exist before.

**Comment by Starli0n** [comment]
Is it Ok for you now?

**Comment by craig-davis** [comment]
@Starli0n I am very sorry that this was not merged in a timely manner. We need to give this project some love and attention. I'm going to add you as a contributor as well.

**Comment by Starli0n** [comment]
Thank you for adding me as contributor.
I really appreciate it :-)

**Comment by craig-davis** [comment]
@Starli0n Thank you for contributing! 

Next on my list it to get this upgraded to phpunit 6. I've been short on time lately, but it's a goal.

**Pull request merged**
